site_name: 'Human-AI Interaction (Fall 2020)'
site_url: 'https://haiicmu.github.io/'
site_description: 'Human-AI Interaction (Fall 2020)'
site_author: 'Steven Wu & Haiyi Zhu'

theme:
  name: 'flatly'
  language: 'en'
  feature:
  tabs: 'true'
  logo: 'assets/images/favicon.ico'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: yellow
    accent: yellow

nav:
  - Home:
    - About: 'index.md'
  - Schedule:
    - Calendar: 'calendar.md'
  - Assignments:
    - Instructions: 'hw/instructions.md'
  - Resources:
    - Python: 'resources/python.md'
    - Related courses: 'resources/others.md'